Traceback (most recent call last):
  File "/Users/alandmesser/anaconda3/envs/workshops/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/alandmesser/anaconda3/envs/workshops/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/alandmesser/anaconda3/envs/workshops/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/alandmesser/anaconda3/envs/workshops/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/alandmesser/anaconda3/envs/workshops/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/Users/alandmesser/anaconda3/envs/workshops/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/alandmesser/anaconda3/envs/workshops/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/alandmesser/anaconda3/envs/workshops/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
X_ = datasets['X_train']
factor = 1.5
q1 = X_.quantile(0.25)
q3 = X_.quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (factor * iqr)
upper_bound = q3 + (factor * iqr)
X_[((X_ < lower_bound) | (X_ > upper_bound))] = np.nan
X_.isna().sum()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-4-0d05dd7e7ba3>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mX_[0m [0;34m=[0m [0mdatasets[0m[0;34m[[0m[0;34m'X_train'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mfactor[0m [0;34m=[0m [0;36m1.5[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mq1[0m [0;34m=[0m [0mX_[0m[0;34m.[0m[0mquantile[0m[0;34m([0m[0;36m0.25[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mq3[0m [0;34m=[0m [0mX_[0m[0;34m.[0m[0mquantile[0m[0;34m([0m[0;36m0.75[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0miqr[0m [0;34m=[0m [0mq3[0m [0;34m-[0m [0mq1[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'datasets' is not defined
NameError: name 'datasets' is not defined

